#ifndef SESSION_CONFIG_H
#define SESSION_CONFIG_H


enum class SessionCommand {
    NONE = 0, // This is never sent by PI. This is just initial value and can be used for errors
    SESSION_CONFIG_WRIST = 1,
    SESSION_CONFIG_POINTER = 3,
    SESSION_CONFIG_SPO2 = 4,
    SESSION_START = 5,
    SESSION_STOP = 6,
    CALIBRATE_SESSION = 7,
    CALIBRATION_IN_PROGRESS = 8,
    CALIBRATION_COMPLETED = 9,
    SESSION_CONFIG_MIDDLE = 10,
    SESSION_CONFIG_RING = 11,
    SESSION_CONFIG_PINKY = 12,
    SESSION_CONFIG_THUMB = 13,
    SESSION_CONFIG_POINTER_MIDDLE = 14,
    SESSION_CONFIG_POINTER_WRIST = 15,
    SESSION_CONFIG_GRIPPER_POINTER = 16,
    SESSION_CONFIG_GRIPPER_MIDDLE = 17,
    SESSION_CONFIG_GRIPPER_RING = 18,
    SESSION_CONFIG_GRIPPER_PINKY = 19,
    SESSION_CONFIG_GRIPPER_THUMB = 20,
    SESSION_CONFIG_GRIPPER_POINTER_MIDDLE = 21,
    SESSION_CONFIG_GRIPPER_ALL = 22
};

constexpr unsigned int NUM_OF_COMMANDS =
    static_cast<unsigned int>(SessionCommand::SESSION_CONFIG_GRIPPER_ALL) + 1;


#endif
